fix: make the error message when trying to load files from S3 without credentials set up more clear (#165)
tl;dr: Make the error message that occurs when there is an error reading
a `Parquet` file from S3 more clear -- don't choke if there are no S3
credentials, instead pass an exception back with a clear error message.

Previously, if you attempted to `session.read.parquet("s3://...")` and
had no AWS credentials in the credential chain boto checks, you would
get the confusing error

```
fenic.core.error.PlanError: Failed to infer schema from Parquet files
```

You'd have to go up the stack to see the real problem and it was still
confusing:
```
  File "/Users/brandoncallender/dev/fenic/src/fenic/_backends/local/utils/io_utils.py", line 70, in _fetch_and_validate_s3_credentials
    frozen_creds = credentials.get_frozen_credentials()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
```

Fix this by:
- Defensively checking if the credentials from
`session.get_credentials()` are `None` and erroring early if so
- Add the context of the downstream error to the `PlanError` that gets
returned, so the user has a clear path to fixing the issue.

The resulting error looks like:
```
fenic.core.error.PlanError: Failed to infer schema from Parquet files: Unable to locate AWS credentials.
```

which should provide some more useful context. 


Note: In general we might need to rethink how we are doing the S3
integration -- when pulling files from a public bucket, you don't
actually strictly need any AWS credentials, so this could be confusing
for a user that attempts to pull from a public bucket and expects it to
work without providing credentials.